room_dict = {         #1     #2     #3     #4     #top   #bot   #left  #right #MT    #b_L   #b_R   #b_T   #b_B    left,   right, up,    down
              "1"  :[[False, False, True,  False, True,  False, True,  False, False, False, False, False, False], [False, True,  False, True ]],
              "2"  :[[False, False, True,  True,  True,  False, False, False, False, False, False, False, False], [True,  True,  False, True ]],
              "3"  :[[True,  True,  True,  True,  False, False, False, False, True,  False, False, False, True ], [True,  True,  False, True ]],
              "4"  :[[False, False, False, True,  True,  False, False, True,  False, False, False, False, False], [True,  False, False, True ]],
              "5"  :[[False, True,  False, False, False, True,  True,  False, False, False, False, False, False], [False, True,  True,  False]],
              "6"  :[[True,  True,  True,  True,  False, False, False, False, False, True,  False, False, False], [True,  True,  True,  True ]],
              "7"  :[[True,  True,  True,  True,  False, False, False, False, False, False, False, False, False], [True,  True,  True,  True ]],
              "8"  :[[True,  False, False, True,  False, False, False, True,  False, False, False, False, False], [True,  False, True,  True ]],
              "9"  :[[False, False, True,  False, True,  False, True,  False, False, False, False, False, False], [False, True,  False, True ]],
              "10" :[[True,  True,  True,  True,  False, False, False, False, False, False, False, False, False], [True,  True,  True,  True ]],
              "11" :[[True,  True,  True,  True,  False, False, False, False, False, True,  True,  False, True ], [True,  True,  True,  True ]],
              "12" :[[True,  True,  True,  True,  False, False, False, False, False, False, True,  False, False], [True,  True,  True,  True ]],
              "13" :[[False, False, False, False, False, False, True,  True,  False, False, False, False, True ], [False, False, True,  True ]],
              "14" :[[True,  True,  False, False, False, True,  True,  False, False, False, False, False, False], [False, True,  True,  False]],
              "15" :[[True,  True,  True,  True,  False, False, False, False, False, False, False, False, False], [True,  True,  True,  True ]],
              "16" :[[True,  False, False, True,  False, False, False, True,  False, False, False, False, False], [True,  False, True,  True ]],
              "17" :[[False, True,  True,  False, False, False, True,  False, False, False, False, False, False], [False, True,  True,  True ]],
              "18" :[[False, False, False, False, True,  True,  False, False, False, False, False, False, False], [True,  True,  False, False]],
              "19" :[[True,  True,  True,  True,  False, False, False, False, False, False, False, False, False], [True,  True,  True,  True ]],
              "20" :[[True,  False, False, False, False, True,  False, True, False,  False, False, False, False], [True,  False, True,  False]],
              "21" :[[True,  True,  True,  True,  False, False, False, False, False, True,  False, True,  False], [True,  True,  True,  True ]],
              "22" :[[False, False, True,  True,   True, False, False, False, False, False, False, False, False], [True,  True,  False, True ]],
              "23" :[[True,  True,  True,  True,  False, False, False, False, False, False, False, False, False], [True,  True,  True,  True ]],
              "24" :[[False, False, False, True,  True,  False, False, True,  False, False, False, False, False], [True,  False, False, True ]],
              "25" :[[False, True,  False, False, False, True,  True,  False, False, False, False, False, False], [False, True,  True,  False]],
              "26" :[[True,  True,  False, False, False, True,  False, False, False, False, True,  False, False], [True,  True,  True,  False]],
              "27" :[[True,  False, False, False, False, True,  False, True, False, False,  False, False, False], [True,  False, True,  False]],
              "28" :[[False, False, False, False, False, True,  True,  True,  False, False, False, False, False], [False, False, False, False]]
              }

cur_room = 3
